// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektWWW.NET_FR_LB.Data;

#nullable disable

namespace ProjektWWW.NET_FR_LB.Migrations
{
    [DbContext(typeof(Kantor1DbContext))]
    [Migration("20250612014506_migracjaDUZA")]
    partial class migracjaDUZA
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Komentarz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<string>("NazwaPliku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uzytkownik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Komentarze");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.AlertKursu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktywny")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataUtworzenia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PowiadomGdyMniejszy")
                        .HasColumnType("bit");

                    b.Property<double>("ProgKursu")
                        .HasColumnType("float");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("WalutaDoId")
                        .HasColumnType("int");

                    b.Property<int>("WalutaZId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.HasIndex("WalutaDoId");

                    b.HasIndex("WalutaZId");

                    b.ToTable("AlertyKursow");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Powiadomienie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Przeczytane")
                        .HasColumnType("bit");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UzytkownikId");

                    b.ToTable("Powiadomienia");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Rola", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NazwaRoli")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rola");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Uzytkownik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRejestracji")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HasloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uzytkownicy");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.UzytkownikRola", b =>
                {
                    b.Property<int>("UzytkownikId")
                        .HasColumnType("int");

                    b.Property<int>("RolaId")
                        .HasColumnType("int");

                    b.HasKey("UzytkownikId", "RolaId");

                    b.HasIndex("RolaId");

                    b.ToTable("UzytkownikRole");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Waluta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kraj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Waluty");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Kod = "USD",
                            Kraj = "🇺🇸",
                            Nazwa = "Dolar amerykański",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 101,
                            Kod = "EUR",
                            Kraj = "🇪🇺",
                            Nazwa = "Euro",
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 102,
                            Kod = "GBP",
                            Kraj = "🇬🇧",
                            Nazwa = "Funt brytyjski",
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 103,
                            Kod = "PLN",
                            Kraj = "🇵🇱",
                            Nazwa = "Złoty polski",
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = 104,
                            Kod = "JPY",
                            Kraj = "🇯🇵",
                            Nazwa = "Jen japoński",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 105,
                            Kod = "CHF",
                            Kraj = "🇨🇭",
                            Nazwa = "Frank szwajcarski",
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 106,
                            Kod = "AUD",
                            Kraj = "🇦🇺",
                            Nazwa = "Dolar australijski",
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = 107,
                            Kod = "CAD",
                            Kraj = "🇨🇦",
                            Nazwa = "Dolar kanadyjski",
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 108,
                            Kod = "NOK",
                            Kraj = "🇳🇴",
                            Nazwa = "Korona norweska",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 110,
                            Kod = "SEK",
                            Kraj = "🇸🇪",
                            Nazwa = "Korona szwedzka",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 111,
                            Kod = "CNY",
                            Kraj = "🇨🇳",
                            Nazwa = "Juan chiński",
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 112,
                            Kod = "NZD",
                            Kraj = "🇳🇿",
                            Nazwa = "Dolar nowozelandzki",
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Id = 113,
                            Kod = "CZK",
                            Kraj = "🇨🇿",
                            Nazwa = "Korona czeska",
                            Symbol = "Kč"
                        },
                        new
                        {
                            Id = 114,
                            Kod = "DKK",
                            Kraj = "🇩🇰",
                            Nazwa = "Korona duńska",
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 115,
                            Kod = "HUF",
                            Kraj = "🇭🇺",
                            Nazwa = "Forint węgierski",
                            Symbol = "Ft"
                        },
                        new
                        {
                            Id = 116,
                            Kod = "ZAR",
                            Kraj = "🇿🇦",
                            Nazwa = "Rand południowoafrykański",
                            Symbol = "R"
                        },
                        new
                        {
                            Id = 117,
                            Kod = "ILS",
                            Kraj = "🇮🇱",
                            Nazwa = "Nowy izraelski szekel",
                            Symbol = "₪"
                        },
                        new
                        {
                            Id = 118,
                            Kod = "MXN",
                            Kraj = "🇲🇽",
                            Nazwa = "Peso meksykańskie",
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 119,
                            Kod = "TRY",
                            Kraj = "🇹🇷",
                            Nazwa = "Lira turecka",
                            Symbol = "₺"
                        },
                        new
                        {
                            Id = 120,
                            Kod = "SGD",
                            Kraj = "🇸🇬",
                            Nazwa = "Dolar singapurski",
                            Symbol = "S$"
                        });
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.AlertKursu", b =>
                {
                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Waluta", "WalutaDo")
                        .WithMany()
                        .HasForeignKey("WalutaDoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Waluta", "WalutaZ")
                        .WithMany()
                        .HasForeignKey("WalutaZId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");

                    b.Navigation("WalutaDo");

                    b.Navigation("WalutaZ");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Powiadomienie", b =>
                {
                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Uzytkownik", "Uzytkownik")
                        .WithMany()
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.UzytkownikRola", b =>
                {
                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Rola", "Rola")
                        .WithMany("UzytkownikRole")
                        .HasForeignKey("RolaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektWWW.NET_FR_LB.Models.Uzytkownik", "Uzytkownik")
                        .WithMany("UzytkownikRole")
                        .HasForeignKey("UzytkownikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rola");

                    b.Navigation("Uzytkownik");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Rola", b =>
                {
                    b.Navigation("UzytkownikRole");
                });

            modelBuilder.Entity("ProjektWWW.NET_FR_LB.Models.Uzytkownik", b =>
                {
                    b.Navigation("UzytkownikRole");
                });
#pragma warning restore 612, 618
        }
    }
}
